# Create container with:
# docker build -t her .
# Run container with (replacing /path/to/hindsight/repo):
# docker run --privileged --rm -v /path/to/hindsight/repo:/root --runtime nvidia --network host --name herdev -it her

# This preinstalls pytorch, python, pip3. 
FROM nvcr.io/nvidia/l4t-pytorch:r32.4.4-pth1.6-py3

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y
RUN apt-get upgrade -y

# libopenmpi-dev is required for mpi4py
RUN apt-get install -y libopenmpi-dev

# Repo requirements
RUN pip3 -vv install mpi4py
# This takes ~30 mins. -vv makes it print more data so you know it still working
RUN pip3 -vv install gym

# Useful tools. More will likely need to be added.
RUN apt-get install -y git man curl gdb openssh-client

